### ISSUE TITLE
360dataset 

### ISSUE THREAD

**Issue by zhijieshen-bjtu** [HAL-lucination/segfuse#2]
How can I get the dataset? In fact, I have fill the table many times, but I still can not get it.

**Comment by delusique** [comment]
Thank you for your interest in our work. I have directly replied with email, please take a look.

**Comment by hyabc12321** [comment]
I'd like to ask for the dataset too. Could you send it to me?

**Comment by Qsminefor** [comment]
Hi, I also try to get this dataset and fill the table. What should I do to get it?

> Thank you for your interest in our work. I have directly replied with email, please take a look.

**Comment by luislofer89** [comment]
Hi. I'm also interested in the dataset. I used the request form but no answer received. Is there a different way to access the data?
